version: "3.7"

services:
    # image project
    app:
        build:
            context: ./portal-noticias-api
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "9191:80"
        volumes:
            - ./:/var/www
            - ./portal-noticias-api/docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # db mysql
    db:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
            MYSQL_USER: ${DB_USERNAME:-username}
        volumes:
            - ./portal-noticias-api/.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3389:3306"
        networks:
            - laravel

    # redis
    redis:
        image: redis:latest
        networks:
            - laravel

    frontend:
        build:
            context: ./portal-noticias-front
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "8080:80"  # Mapeie a porta 80 do container para a porta 8080 do host
        networks:
            - laravel
       


networks:
    laravel:
        driver: bridge
